version: "3"

services:
  wallet-manager:
    image: giorgioxlabs/wallet-manager
    ports:
      - "50051:50051"
    volumes:
      - "./config.json:/etc/wallet-manager/config.json"
    restart: always
